# Generated by Django 5.0.6 on 2024-05-29 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plans_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dzien',
            new_name='Day',
        ),
    ]
